# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crnn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crnn.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncrnn.proto\"H\n\x0b\x63rnnRequest\x12\x11\n\timageData\x18\x01 \x01(\x0c\x12\x11\n\timageUUID\x18\x02 \x01(\t\x12\x13\n\x0binformation\x18\x03 \x01(\t\"G\n\x10\x63rnnResponseData\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\t\x12\x13\n\x0binformation\x18\x03 \x01(\t\"b\n\x0c\x63rnnResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\t\x12\x13\n\x0bresponseMSG\x18\x02 \x01(\t\x12\'\n\x0cresponseData\x18\x03 \x01(\x0b\x32\x11.crnnResponseData2-\n\x04\x63rnn\x12%\n\x04\x63rnn\x12\x0c.crnnRequest\x1a\r.crnnResponse\"\x00\x62\x06proto3'
)




_CRNNREQUEST = _descriptor.Descriptor(
  name='crnnRequest',
  full_name='crnnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageData', full_name='crnnRequest.imageData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageUUID', full_name='crnnRequest.imageUUID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='information', full_name='crnnRequest.information', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=86,
)


_CRNNRESPONSEDATA = _descriptor.Descriptor(
  name='crnnResponseData',
  full_name='crnnResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='crnnResponseData.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='crnnResponseData.score', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='information', full_name='crnnResponseData.information', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=159,
)


_CRNNRESPONSE = _descriptor.Descriptor(
  name='crnnResponse',
  full_name='crnnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='crnnResponse.responseCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMSG', full_name='crnnResponse.responseMSG', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseData', full_name='crnnResponse.responseData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=259,
)

_CRNNRESPONSE.fields_by_name['responseData'].message_type = _CRNNRESPONSEDATA
DESCRIPTOR.message_types_by_name['crnnRequest'] = _CRNNREQUEST
DESCRIPTOR.message_types_by_name['crnnResponseData'] = _CRNNRESPONSEDATA
DESCRIPTOR.message_types_by_name['crnnResponse'] = _CRNNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

crnnRequest = _reflection.GeneratedProtocolMessageType('crnnRequest', (_message.Message,), {
  'DESCRIPTOR' : _CRNNREQUEST,
  '__module__' : 'crnn_pb2'
  # @@protoc_insertion_point(class_scope:crnnRequest)
  })
_sym_db.RegisterMessage(crnnRequest)

crnnResponseData = _reflection.GeneratedProtocolMessageType('crnnResponseData', (_message.Message,), {
  'DESCRIPTOR' : _CRNNRESPONSEDATA,
  '__module__' : 'crnn_pb2'
  # @@protoc_insertion_point(class_scope:crnnResponseData)
  })
_sym_db.RegisterMessage(crnnResponseData)

crnnResponse = _reflection.GeneratedProtocolMessageType('crnnResponse', (_message.Message,), {
  'DESCRIPTOR' : _CRNNRESPONSE,
  '__module__' : 'crnn_pb2'
  # @@protoc_insertion_point(class_scope:crnnResponse)
  })
_sym_db.RegisterMessage(crnnResponse)



_CRNN = _descriptor.ServiceDescriptor(
  name='crnn',
  full_name='crnn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=306,
  methods=[
  _descriptor.MethodDescriptor(
    name='crnn',
    full_name='crnn.crnn',
    index=0,
    containing_service=None,
    input_type=_CRNNREQUEST,
    output_type=_CRNNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRNN)

DESCRIPTOR.services_by_name['crnn'] = _CRNN

# @@protoc_insertion_point(module_scope)
